events {}

http {
    upstream user_service {
        server user-service:3001;
    }

    upstream order_service {
        server order-service:3002;
    }

    server {
        listen 80;

        location /users/ {
            proxy_pass http://user_service/;
            proxy_set_header Host $host;
        }

        location /orders/ {
            proxy_pass http://order_service/;
            proxy_set_header Host $host;
        }
    }
}